build: server.cpp client.cpp
	g++-14 -o server server.cpp -I/opt/homebrew/Cellar/nlohmann-json/3.11.3/include/
	g++-14 -o client client.cpp -I/opt/homebrew/Cellar/nlohmann-json/3.11.3/include/

clean:
	rm -f server client output.txt